name: Run Commands on VM

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest
    env: ${{ secrets }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Commands on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 1000s
          script: |
            # Run your commands on the VM
            whoami
            id
            sudo rm -rf /var/www/html*
            sudo git clone https://github.com/varuncobain/action.git /var/www/html

    
