name: scp files
on: [push]
jobs:
 build:
  name: copy file via ssh
  runs-on: self-hosted
  steps:
  - uses: appleboy/scp-action@v0.1.4
    with:
     host: ${{ secrets.HOST }}
     username: ${{ secrets.USERNAME }}
     port: ${{ secrets.PORT }}
     key: ${{ secrets.KEY }}
     source: "tests/a.txt,tests/b.txt"
     target: your_server_target_folder_path 
