name: scp files

on: [push]

jobs:

build:

  name: copy file via ssh

  runs-on: ubuntu-latest

  steps:

  - uses: appleboy/scp-action@v0.1.4

    with:

     host: 4.236.144.47

     username: vivek

     port: 22

     password: Password@123
     timeout: 1000s
     source: .

     target: /home/vivek/test
    
