name: Run Commands on VM

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Commands on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 1000s
          script: |
            # Run your commands on the VM
            whoami
            ls -la 
            # Additional commands...
    
