name: scp files
on:
  push:
    branches:
      - main
jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  steps:
  - uses: appleboy/scp-action@v0.1.4
  - name: copy file via ssh
    with:
      host: 4.236.144.47
      username: vivek
      port: 22
      password: Password@123
      timeout: 1000s
      source: .
      target: /home/vivek/test
    
