name: scp files
on: [push]
jobs:
 build:
  name: copy file via ssh
  runs-on: ubuntu-latest
  steps:
  - uses: garygrossgarten/github-action-scp@release
    with:
     host: 4.236.144.47
     username: vivek
     password: Password@123
     local: action
     remote: scp/directory

    
