name: scp files
on: [push]
jobs:
 build:
  name: copy file via ssh
  runs-on: ubuntu-latest
  steps:
  - uses: appleboy/scp-action@v0.1.4
    with:
     host: ${{ secrets.VM_HOST }}
     username: ${{ secrets.VM_USERNAME }}
     port: ${{ secrets.PORT }}
     key: ${{ secrets.VM_PASSWORD }}
     source: .
     target: /home/vivek/test
